# Generated by Django 3.0.8 on 2020-07-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkewCorrector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='processed_cover',
            field=models.ImageField(blank=True, upload_to='output/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
